### PR TITLE
Prepare script

### PR DESCRIPTION
**Pull request by Drachenkaetzchen**
Here's the prepare script which does (hopefully) all required changes to the project configuration according to [Building the Source Code](https://github.com/obiwanjacobi/vst.net/blob/master/doc/Building_the_Source_Code.md)

- I skipped "Permanently remove source control bindings" as I did not knew what this meant.
- `REM out the gacutil call in post build events (Core & Framework)` doesn't seem to be there anymore

Howto:
- Download Visual Studio 2017
- Download Visual Studio 2012 trial (to compile as-is), haven't tried changing the platform toolset to something else, but might worth a try
- Clone the repository
- Execute the `Source/Build/Prepare.ps1` script - this adjusts all project configuration files (you might need to set your execution policy by `set-executionpolicy unrestricted -scope CurrentUser`
- Open the Master Solution in Visual Studio 2017 (only CLR4 works for now, CLR2 doesn't)
- Click "Rebuild Solution" and be very happy that everything compiles in one go (hopefully)

### CODE REVIEW

**Comment by obiwanjacobi** [comment]
Hi thanks for the script. I have two thoughts:

1. I don't like mixing a build-prepare script with changes to the stdafx.h. To me they feel like two different things. Also I have no time to verify the code changes right now (no CI build setup).
2. I think the Prepare script should be somewhere else. The Build folder is (currently) meant for making release builds - not a folder anyone would need for 'normal' operation. Perhaps we should put the Prepare script in the root (.sln) and call it PrepareCompile or something...

What do you think - makes sense?

**Comment by Drachenkaetzchen** [comment]
Fair points, I'll remove the stdafx.h change for now (it's a single #define only), but it could take a bit :)

**Comment by Drachenkaetzchen** [comment]
Sorry for not updating the PR so far, but I've been pretty busy. However, I was finally able to send a donation. Thank you at this point for vst.net!

**Comment by obiwanjacobi** [comment]
I'm closing this PR due to inactivity and the fact that VST.NET 1 is becoming less relevant...
Please resubmit if you wish to pursue this.

**Pull request closed without merging**
